In [1]:
import tt
from tt.amen import amen_solve

In [66]:
d = 5
n = 2**d
delta_x = 1 / n
print(delta_x)

0.03125


In [67]:
# second derivative

delta_2 = tt.qlaplace_dd([d])

print(delta_2.full())
delta_2 = delta_2 * (1/(2*delta_x))
print(type(delta_2))
print(delta_2.full())

[[ 2. -1.  0. ...  0.  0.  0.]
 [-1.  2. -1. ...  0.  0.  0.]
 [ 0. -1.  2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  2. -1.  0.]
 [ 0.  0.  0. ... -1.  2. -1.]
 [ 0.  0.  0. ...  0. -1.  2.]]
<class 'tt.core.matrix.matrix'>
[[ 32. -16.   0. ...   0.   0.   0.]
 [-16.  32. -16. ...   0.   0.   0.]
 [  0. -16.  32. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...  32. -16.   0.]
 [  0.   0.   0. ... -16.  32. -16.]
 [  0.   0.   0. ...   0. -16.  32.]]


In [68]:
# first derivative 

t = tt.delta(2, d, center = 1)
delta_1 = tt.Toeplitz(t, kind = 'L') - tt.Toeplitz(t, kind = 'L').T
# delta_1 = delta_1.round(1e-14)

print(delta_1.full())
delta_1 = delta_1 * (1/delta_x**2)
print(type(delta_1))
print(delta_1.full())

[[ 0.  1.  0. ...  0.  0.  0.]
 [-1.  0.  1. ...  0.  0.  0.]
 [ 0. -1.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ... -1.  0.  1.]
 [ 0.  0.  0. ...  0. -1.  0.]]
<class 'tt.core.matrix.matrix'>
[[    0.  1024.     0. ...     0.     0.     0.]
 [-1024.     0.  1024. ...     0.     0.     0.]
 [    0. -1024.     0. ...     0.     0.     0.]
 ...
 [    0.     0.     0. ...     0.  1024.     0.]
 [    0.     0.     0. ... -1024.     0.  1024.]
 [    0.     0.     0. ...     0. -1024.     0.]]


In [69]:
Id = tt.eye(2, d)
Id.full()

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [77]:
A = tt.kron(delta_1, Id) + tt.kron(delta_1, delta_2)
# A = A.round(1e-14)
x = tt.ones(2,2*d)
f_0 = tt.rand(n,2*d,r=2)
y = amen_solve(A,f_0,x,1e-6)

In [78]:
y.full()

array([[[[[[[[[[ 1.12610788e-04,  5.38810155e-04],
               [ 2.34139158e-05, -9.16011356e-04]],

              [[ 8.19054212e-04,  1.03511672e-03],
               [ 5.30231024e-04, -8.75759384e-04]]],


             [[[ 1.17612401e-03,  1.07796657e-03],
               [ 8.76348588e-04, -1.07628260e-03]],

              [[ 6.41820554e-04,  2.50157275e-04],
               [ 2.57849264e-04, -1.33756755e-03]]]],



            [[[[ 3.66966531e-05, -8.54966050e-05],
               [-1.64663029e-04, -5.59259090e-04]],

              [[ 7.39503363e-04,  4.92044230e-04],
               [ 4.76580767e-04, -7.30651728e-04]]],


             [[[ 1.09492499e-04,  7.69587750e-05],
               [ 4.21925175e-05, -7.89324996e-04]],

              [[-1.94609410e-04, -8.15056586e-04],
               [ 1.53642787e-04,  5.30711055e-05]]]]],




           [[[[[-4.03729043e-04, -7.52843349e-04],
               [-1.08084729e-03, -1.45260784e-03]],

              [[ 3.31011074e-04,  8.08321910e-05],